export const TRANSACTIONFEES_LOADING = "TRANSACTIONFEES_LOADING";
export const TRANSACTIONFEES_LOADED = "TRANSACTIONFEES_LOADED";
export const TRANSACTIONFEES_SUCCESS = "TRANSACTIONFEES_SUCCESS";
export const TRANSACTIONFEES_ERROR = "TRANSACTIONFEES_ERROR";

export const GASFEES_LOADING = "GASFEES_LOADING";
export const GASFEES_LOADED = "GASFEES_LOADED";
export const GASFEES_SUCCESS = "GASFEES_SUCCESS";
export const GASFEES_ERROR = "GASFEES_ERROR";

export const FILE_UPLOADING = "FILE_UPLOADING";
export const FILE_UPLOADED = "FILE_UPLOADED";
export const FILEUPLOADING_ERROR = "FILEUPLOADING_ERROR";